[package]
name = "map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_macros = { path = "../../shared/term_macros"}
cmd_lib = "1.3.0"
crossbeam = "0.8"