[package]
name = "ngrams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_macros = { path = "../../shared/term_macros" }
rayon = "1.5.3"
memmap = "0.7.0"
dashmap = "5.3"