[[bin]]
name = "dedup"
path = "deduplicate.rs"

[dependencies]
fnv = "1.0.7"
nohash-hasher = "0.2.0"

[dependencies.term_macros]
path = "../../shared/term_macros"

[package]
authors = ["Anonymous"]
edition = "2018"
name = "deduplicate"
version = "0.1.0"
