[package]
name = "pixelui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.7.2"
rayon = "1.5.2"
unic-char-range = "0.9"
term_size = "0.3"
image = "*"