[package]
name = "kw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rake = "0.3.3"
term_macros = {path = "../../shared/term_macros" }