[package]
name = "kv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jammdb = "0.5"
unqlite = "1.5.0"

[dependencies.term_macros]
path = "../../shared/term_macros"