[package]
name = "canslate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
unicode-segmentation = "1.7.1"
memmap = "*"

[dependencies.term_macros]
path = "../../shared/term_macros"