[package]
name = "kv2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heed = "0.11"
miniserde = "0.1"

[dependencies.term_macros]
path = "../../shared/term_macros"