[[bin]]
name = "ascii"
path = "ascii.rs"

[dependencies]
any_ascii = "0.3.1"

[dependencies.term_macros]
path = "../../shared/term_macros"

[package]
authors = ["Anonymous"]
edition = "2018"
name = "ascii"
version = "0.1.0"
