[package]
name = "stringy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
ropey = "*"
lasso = "*"
once_cell = "*"