[package]
name = "improv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd_lib = "1.3"
miniserde = "0.1"
minreq = { version = "2.6.0", features = ["https-bundled-probe"] }